language: node_js
node_js:
  - '0.10'
script: 'npm test'
after_success:
  - npm run build
before_script:
  # quotation from https://github.com/FWeinb/node-webkit-screenshot/blob/master/.travis.yml#L8
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start +extension RANDR;
  - sudo apt-get -qq update
  - sudo apt-get -y install libx11-6:i386;
  - sudo apt-get -y install libglib2.0-0:i386;
  - sudo apt-get -y install libgtk2.0-0:i386;
  - sudo apt-get -y install libatk1.0-0:i386;
  - sudo apt-get -y install libgdk-pixbuf2.0-0:i386;
  - sudo apt-get -y install libcairo2:i386;
  - sudo apt-get -y install libfreetype6:i386;
  - sudo apt-get -y install libfontconfig1:i386;
  - sudo apt-get -y install libxcomposite1:i386;
  - sudo apt-get -y install libasound2:i386;
  - sudo apt-get -y install libxdamage1:i386;
  - sudo apt-get -y install libxext6:i386;
  - sudo apt-get -y install libxfixes3:i386;
  - sudo apt-get -y install libnss3:i386;
  - sudo apt-get -y install libnspr4:i386;
  - sudo apt-get -y install libgconf-2-4:i386;
  - sudo apt-get -y install libexpat1:i386;
  - sudo apt-get -y install libdbus-1-3:i386;
  - sudo apt-get -y install libudev0:i386;

deploy:
  provider: releases
  api_key:
    secure: maQNx7F2Rn8CztN6whOwEUbOcaIGDKeYn5WmaZShrSAMjA6GkO2C/Zl1cirRZiUwZfxDEdZGMh5gBDu/r65R8vlnZJqYDWVf7nB3She1RjqmrCoKd5W+5d0lpxSmPzK1SHF7JwhcZ65+2dwhdqcJ6H/KpM8nB3CT0XOSDJAsJ8k=
  file:
    - build/midnight-osx32.zip
    - build/midnight-osx64.zip
    - build/midnight-win32.zip
    - build/midnight-win64.zip
  on:
    repo: 59naga/midnight
    tags: true
    all_branches: true
  skip_cleanup: true