sudo: false
language: node_js
node_js:
  # - iojs
  # - 0.11
  - 0.12
before_install:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16 -extension RANDR"
script:
  - npm test
after_success:
  - npm run build

deploy:
  provider: releases
  api_key:
    secure: maQNx7F2Rn8CztN6whOwEUbOcaIGDKeYn5WmaZShrSAMjA6GkO2C/Zl1cirRZiUwZfxDEdZGMh5gBDu/r65R8vlnZJqYDWVf7nB3She1RjqmrCoKd5W+5d0lpxSmPzK1SHF7JwhcZ65+2dwhdqcJ6H/KpM8nB3CT0XOSDJAsJ8k=
  file:
    - build/midnight-osx32.zip
    - build/midnight-osx64.zip
    - build/midnight-win32.zip
    - build/midnight-win64.zip
  on:
    repo: 59naga/midnight
    tags: true
    all_branches: true
  skip_cleanup: true